import type { NextPage } from "next";
import Head from "next/head";

import { client } from "../lib/client";

const Home: NextPage = ({ products }) => {
  console.log(products);

  return (
    <div>
      <Head>
        <title>Futbol Jersey Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>{products?.map((product) => product.name)}</div>
      </main>
    </div>
  );
};

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  return { props: { products } };
};

export default Home;
