import Head from "next/head";
import { useAppContext } from "../contexts/AppContext";
import Navbar from "../components/Navbar";

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  const { showCart } = useAppContext();

  return (
    <div className="flex h-screen flex-col">
      <Head>
        <title>Futbol Jersey Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Navbar />

      <main className={`flex-1 ${showCart ? "overflow-auto" : ""}`}>
        {children}
      </main>
    </div>
  );
};

export default Layout;
