import Head from "next/head";
import Navbar from "../components/Navbar";

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <div className="h-screen">
      <Head>
        <title>Futbol Jersey Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <Navbar />

      <main>{children}</main>
    </div>
  );
};

export default Layout;
